version: '3'

name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config:/config
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/Downloads/torrents:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/jackett/downloads:/downloads
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/jackett/config:/config
    ports:
      - '9117:9117'

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/radarr:/movies
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/sonarr:/tv
      - //srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/bazarr/appdata/config:/config
    ports:
      - '6767:6767'

  overseerr:
    image: sctx/overseerr
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PORT=5055
    volumes:
      - //srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/overseerr/config:/app/config
    ports:
      - '5055:5055'

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    depends_on:
      - flaresolverr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/prowlarr/config:/config
    ports:
      - '9696:9696'

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/flaresolverr/config:/config
    ports:
      - '8191:8191'

  
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/configradarr/appdata/config:/config
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/Downloads/torrents:/downloads
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/Videos/radarr/movies:/movies
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/Videos/radarr/anime:/anime
    ports:
      - '7878:7878'


  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/sonarr/appdata/config:/config
      - /mnt/terachad/Videos/sonarr:/tv
      - /mnt/terachad/Downloads/torrents:/downloads
    ports:
      - '8989:8989'

  plex:
    image: plexinc/pms-docker:latest
    shm_size: '2gb'
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - VA_DRIVER=IHD
    volumes:
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/plex/config:/config
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/plex/data:/data
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/plex/transcode:/transcode
      - /srv/dev-disk-by-uuid-23af3f9d-fc96-4479-8c82-cc12c98658c7/Dados/config/Videos:/media
  
   
